### ISSUE TITLE
KeyError: 'layerFile' issue

### ISSUE THREAD

**Issue by rishabhbanga** [AMLResearchProject/AML-ALL-Classifiers#41]
**Describe the bug**
While following the steps as mentioned in the article- https://software.intel.com/en-us/articles/detecting-acute-lymphoblastic-leukemia-using-caffe-openvino-neural-compute-stick-2-part-1?fbclid=IwAR15wmR-qw10GfVuaswuLV6RGcPqx3PLyXY8x1gLEv_ijdyxjkfwOHcapQA , I tried running the command to check the Network configuration using python Info.py NetworkInfo, and that's when I got the error. Logs provided in later section.

**To Reproduce**
1. Follow the steps up till installing any requirements using Setup.sh and then check the network config.
2. See error

**Expected behavior**
Should have worked as intended,i.e. show the network being created properly.

**Actual behavior**
python Info.py NetworkInfo
2019-03-20 23:31:51|allCNN|Status: Init complete
Traceback (most recent call last):
  File "Info.py", line 177, in <module>
    main(sys.argv[1:])
  File "Info.py", line 155, in main
    allCNN.loadCaffeNet()
  File "Info.py", line 62, in loadCaffeNet
    self.net = caffe.Net(self.confs["Settings"]["Classifier"]["layerFile"], caffe.TEST)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04 LTS]
 - Hardware: [UP2 Board]

**Comment by AdamMiltonBarker** [comment]
Hi @rishabhbanga thanks for the bug report. The fix will be pushed soon.

**Comment by AdamMiltonBarker** [comment]
Issue should now be resolved with: https://github.com/AMLResearchProject/AML-ALL-Classifiers/pull/42
